let names = [
  "Abílio Santana ",
  "Abou Anni",
  "Acácio Favacho",
  "Adolfo Viana",
  "Adriana Ventura",
  "Adriano do Baldy",
  "Aécio Neves",
  "Aelton Freitas",
  "Afonso Florence",
  "Afonso Hamm",
  "Afonso Motta",
  "Aguinaldo Ribeiro",
  "Airton Faleiro",
  "AJ Albuquerque",
  "Alan Rick",
  "Alceu Moreira",
  "Alcides Rodrigues",
  "Alê Silva",
  "Alencar Santana",
  "Alessandro Molon",
  "Alex Manente",
  "Alex Santana",
  "Alexandre Frota",
  "Alexandre Leite",
  "Alexandre Padilha",
  "Alexis Fonteyne",
  "Alice Portugal",
  "Aliel Machado",
  "Aline Gurgel",
  "Aline Sleutjes",
  "Altineu Côrtes",
  "Aluisio Mendes",
  "Amaro Neto",
  "André Abdon",
  "André de Paula",
  "André Ferreira",
  "André Figueiredo",
  "André Fufuca",
  "André Janones",
  "Angela Amin",
  "Antonio Brito",
  "Arlindo Chinaglia",
  "Arnaldo Jardim",
  "Aroldo Martins",
  "Arthur Lira",
  "Arthur Oliveira Maia",
  "Átila Lins",
  "Átila Lira",
  "Augusto Coutinho",
  "Áurea Carolina",
  "Aureo Ribeiro",
  "Bacelar",
  "Baleia Rossi",
  "Benedita da Silva",
  "Benes Leocádio",
  "Beto Faro",
  "Beto Pereira",
  "Beto Rosado",
  "Bia Kicis",
  "Bibo Nunes",
  "Bilac Pinto",
  "Bira do Pindaré",
  "Bohn Gass",
  "Bosco Costa",
  "Bosco Saraiva",
  "Bozzella",
  "Cacá Leão",
  "Camilo Capiberibe",
  "Capitão Alberto Neto",
  "Capitão Augusto",
  "Capitão Derrite",
  "Capitão Fábio Abreu",
  "Carla Dickson",
  "Carla Zambelli",
  "Carlos Chiodini",
  "Carlos Gomes",
  "Carlos Henrique Gaguim",
  "Carlos Jordy",
  "Carlos Sampaio",
  "Carlos Veras",
  "Carlos Zarattini",
  "Carmen Zanotto",
  "Caroline de Toni",
  "Cássio Andrade",
  "Celina Leão",
  "Célio Moura",
  "Célio Silveira",
  "Célio Studart",
  "Celso Maldaner",
  "Celso Russomanno",
  "Celso Sabino",
  "Cezinha de Madureira",
  "Charles Fernandes",
  "Charlles Evangelista",
  "Chico DAngelo",
  "Chiquinho Brazão",
  "Chris Tonietto",
  "Christiane de Souza Yared",
  "Christino Aureo",
  "Clarissa Garotinho",
  "Claudio Cajado",
  "Cleber Verde",
  "Coronel Armando",
  "Coronel Chrisóstomo",
  "Coronel Tadeu",
  "Covatti Filho",
  "Cristiano Vale",
  "Da Vitoria",
  "Dagoberto Nogueira",
  "Damião Feliciano",
  "Daniel Almeida",
  "Daniel Coelho",
  "Daniel Freitas",
  "Daniel Silveira",
  "Daniel Trzeciak",
  "Daniela do Waguinho",
  "Danilo Cabral",
  "Danilo Forte",
  "Danrlei de Deus Hinterholz",
  "Darci de Matos",
  "David Miranda",
  "David Soares",
  "Delegado Antônio Furtado",
  "Delegado Éder Mauro",
  "Delegado Marcelo Freitas",
  "Delegado Pablo",
  "Delegado Waldir",
  "Denis Bezerra",
  "Diego Andrade",
  "Diego Garcia",
  "Dimas Fabiano",
  "Domingos Neto",
  "Domingos Sávio",
  "Dr. Agripino Magalhães",
  "Dr. Frederico",
  "Dr. Jaziel",
  "Dr. Leonardo",
  "Dr. Luiz Antonio Teixeira Jr.",
  "Dr. Luiz Ovando",
  "Dr. Zacharias Calil",
  "Dra. Soraya Manato",
  "Dra. Vanda Milani",
  "Dulce Miranda",
  "Edilázio Júnior",
  "Edio Lopes",
  "Edna Henrique",
  "Eduardo Barbosa",
  "Eduardo Bismarck",
  "Eduardo Bolsonaro",
  "Eduardo Costa",
  "Eduardo Cury",
  "Eduardo da Fonte",
  "Efraim Filho",
  "Elcione Barbalho",
  "Eleuses Paiva",
  "Eli Borges",
  "Eli Corrêa Filho",
  "Elias Vaz",
  "Elmar Nascimento",
  "Emanuel Pinheiro Neto",
  "Emidinho Madeira",
  "Enio Verri",
  "Enrico Misasi",
  "Erika Kokay",
  "Eros Biondini",
  "Euclydes Pettersen",
  "Evair Vieira de Melo",
  "Expedito Netto",
  "Fábio Henrique",
  "Fábio Mitidieri",
  "Fábio Ramalho",
  "Fabio Reis",
  "Fabio Schiochet",
  "Fábio Trad",
  "Fausto Pinato",
  "Felício Laterça",
  "Felipe Carreras",
  "Felipe Francischini",
  "Felipe Rigoni",
  "Félix Mendonça Júnior",
  "Fernanda Melchionna",
  "Fernando Coelho Filho",
  "Fernando Monteiro",
  "Fernando Rodolfo",
  "Filipe Barros",
  "Flávia Arruda",
  "Flávia Morais",
  "Flaviano Melo",
  "Flávio Nogueira",
  "Francisco Jr.",
  "Franco Cartafina",
  "Fred Costa",
  "Frei Anastacio Ribeiro",
  "Gelson Azevedo",
  "Genecias Noronha",
  "General Girão",
  "General Peternelli",
  "Geninho Zuliani",
  "Geovania de Sá",
  "Gervásio Maia",
  "Giacobo",
  "Gil Cutrim",
  "Gilberto Abramo",
  "Gilberto Nascimento",
  "Gilson Marques",
  "Giovani Cherini",
  "Giovani Feltes",
  "Glauber Braga",
  "Glaustin da Fokus",
  "Gleisi Hoffmann",
  "Gonzaga Patriota",
  "Greyce Elias",
  "Guiga Peixoto",
  "Guilherme Mussi",
  "Gurgel",
  "Gustavo Fruet",
  "Gustinho Ribeiro",
  "Gutemberg Reis",
  "Heitor Freire",
  "Heitor Schuch",
  "Helder Salomão",
  "Hélio Costa",
  "Hélio Leite",
  "Helio Lopes",
  "Henrique Fontana",
  "Hercílio Coelho Diniz",
  "Herculano Passos",
  "Hermes Parcianello",
  "Hildo Rocha",
  "Hiran Gonçalves",
  "Hugo Leal",
  "Hugo Motta",
  "Idilvan Alencar",
  "Igor Kannário",
  "Igor Timo",
  "Isnaldo Bulhões Jr.",
  "Ivan Valente",
  "Jandira Feghali",
  "Jaqueline Cassol",
  "Jefferson Campos",
  "Jerônimo Goergen",
  "Jéssica Sales",
  "Jesus Sérgio",
  "Jhonatan de Jesus",
  "João Campos",
  "João Carlos Bacelar",
  "João Daniel",
  "João Maia",
  "João Roma",
  "Joaquim Passarinho",
  "Joenia Wapichana",
  "Joice Hasselmann",
  "Jones Moura",
  "Jorge Braz",
  "Jorge Solla",
  "José Airton Félix Cirilo",
  "José Guimarães",
  "Jose Mario Schreiner",
  "José Medeiros",
  "José Nelto",
  "José Priante",
  "José Ricardo",
  "José Rocha",
  "Joseildo Ramos",
  "Josias Gomes",
  "Josivaldo JP",
  "Juarez Costa",
  "Julian Lemos",
  "Júlio Cesar",
  "Julio Cesar Ribeiro",
  "Júlio Delgado",
  "Juninho do Pneu",
  "Junio Amaral",
  "Júnior Ferrari",
  "Junior Lourenço",
  "Júnior Mano",
  "Juscelino Filho",
  "Kim Kataguiri",
  "Laercio Oliveira",
  "Lafayette de Andrada",
  "Lauriete",
  "Leandre",
  "Leda Sadala",
  "Leo de Brito",
  "Léo Moraes",
  "Léo Motta",
  "Leonardo Gadelha",
  "Leonardo Monteiro",
  "Leônidas Cristino",
  "Leur Lomanto Júnior",
  "Lídice da Mata",
  "Lincoln Portela",
  "Liziane Bayer",
  "Loester Trutis",
  "Lourival Gomes",
  "Lucas Gonzalez",
  "Lucas Redecker",
  "Lucas Vergilio",
  "Luciano Bivar",
  "Luciano Ducci",
  "Lucio Mosquini",
  "Luis Miranda",
  "Luis Tibé",
  "Luisa Canziani",
  "Luiz Antônio Corrêa",
  "Luiz Carlos",
  "Luiz Carlos Motta",
  "Luiz Lima",
  "Luiz Nishimori",
  "Luiz Philippe de Orleans e Bragança",
  "Luiza Erundina",
  "Luizão Goulart",
  "Luizianne Lins",
  "Magda Mofatto",
  "Major Fabiana",
  "Mara Rocha",
  "Marcel van Hattem",
  "Marcelo Álvaro Antônio",
  "Marcelo Aro",
  "Marcelo Calero",
  "Marcelo Freixo",
  "Marcelo Moraes",
  "Marcelo Nilo",
  "Marcelo Ramos",
  "Marcio Alvino",
  "Márcio Biolchi",
  "Márcio Jerry",
  "Márcio Labre",
  "Márcio Macêdo",
  "Márcio Marinho",
  "Marco Bertaiolli",
  "Marcon",
  "Marcos Aurélio Sampaio",
  "Marcos Pereira",
  "Marcos Soares",
  "Margarete Coelho",
  "Maria do Rosário",
  "Maria Rosas",
  "Mariana Carvalho",
  "Marília Arraes",
  "Marina Santos",
  "Mário Heringer",
  "Mário Negromonte Jr.",
  "Marlon Santos",
  "Marreca Filho",
  "Marx Beltrão",
  "Maurício Dziedricki",
  "Mauro Benevides Filho",
  "Mauro Lopes",
  "Mauro Nazif",
  "Merlong Solano",
  "Miguel Lombardi",
  "Milton Coelho",
  "Milton Vieira",
  "Misael Varella",
  "Moses Rodrigues",
  "Natália Bonavides",
  "Nelho Bezerra",
  "Nelson Barbudo",
  "Nereu Crispim",
  "Neri Geller",
  "Neucimar Fraga",
  "Newton Cardoso Jr",
  "Ney Leprevost",
  "Nicoletti",
  "Nilson Pinto",
  "Nilto Tatto",
  "Nivaldo Albuquerque",
  "Norma Ayub",
  "Odair Cunha",
  "Olival Marques",
  "Onyx Lorenzoni",
  "Orlando Silva",
  "Osires Damaso",
  "Osmar Serraglio",
  "Osmar Terra",
  "Ossesio Silva",
  "Otoni de Paula",
  "Ottaci Nascimento",
  "Otto Alencar Filho",
  "Padre João",
  "Paes Landim",
  "Pastor Eurico",
  "Pastor Gil",
  "Pastor Sargento Isidório",
  "Patrus Ananias",
  "Paula Belmonte",
  "Paulão",
  "Paulinho da Força",
  "Paulo Abi-Ackel",
  "Paulo Azi",
  "Paulo Bengtson",
  "Paulo Eduardo Martins",
  "Paulo Foletto",
  "Paulo Freire Costa",
  "Paulo Ganime",
  "Paulo Guedes",
  "Paulo Magalhães",
  "Paulo Marinho Jr",
  "Paulo Pimenta",
  "Paulo Ramos",
  "Paulo Teixeira",
  "Pedro Augusto Bezerra",
  "Pedro Augusto Palareti",
  "Pedro Lucas Fernandes",
  "Pedro Lupion",
  "Pedro Paulo",
  "Pedro Uczai",
  "Pedro Vilela",
  "Pedro Westphalen",
  "Perpétua Almeida",
  "Pinheirinho",
  "Policial Katia Sastre",
  "Pompeo de Mattos",
  "Pr. Marco Feliciano",
  "Professor Alcides",
  "Professor Israel Batista",
  "Professor Joziel",
  "Professora Dayane Pimentel",
  "Professora Dorinha Seabra Rezende",
  "Professora Marcivania",
  "Professora Rosa Neide",
  "Rafael Motta",
  "Raimundo Costa",
  "Raul Henry",
  "Reginaldo Lopes",
  "Rejane Dias",
  "Renata Abreu",
  "Renildo Calheiros",
  "Ricardo Barros",
  "Ricardo da Karol",
  "Ricardo Guidi",
  "Ricardo Izar",
  "Ricardo Silva",
  "Ricardo Teobaldo",
  "Robério Monteiro",
  "Roberto Alves",
  "Roberto de Lucena",
  "Rodrigo Agostinho",
  "Rodrigo Coelho",
  "Rodrigo de Castro",
  "Rogério Correia",
  "Rogério Peninha Mendonça",
  "Ronaldo Carletto",
  "Rosana Valle",
  "Rosangela Gomes",
  "Rose Modesto",
  "Rossoni",
  "RRenato Queiroz",
  "Rubens Bueno",
  "Rubens Otoni",
  "Rubens Pereira Júnior",
  "Rui Falcão",
  "Ruy Carneiro",
  "Sâmia Bomfim",
  "Samuel Moreira",
  "Sanderson",
  "Sandro Alex",
  "Sargento Fahur",
  "Sebastião Oliveira",
  "Sérgio Brito",
  "Sergio Souza",
  "Sergio Toledo",
  "Severino Pessoa",
  "Shéridan",
  "Sidney Leite",
  "Silas Câmara",
  "Silvia Cristina",
  "Silvio Costa Filho",
  "Soraya Santos",
  "Sóstenes Cavalcante",
  "Stefano Aguiar",
  "Subtenente Gonzaga",
  "Tabata Amaral",
  "Tadeu Alencar",
  "Talíria Petrone",
  "Tereza Cristina",
  "Tereza Nelma",
  "Tiago Dimas",
  "Tiago Mitraud",
  "Tiririca",
  "Tito",
  "Toninho Wandscheer",
  "Túlio Gadêlha",
  "Uldurico Junior",
  "Valmir Assunção",
  "Valtenir Pereira",
  "Vander Loubet",
  "Vanderlei Macris",
  "Vavá Martins",
  "Vermelho",
  "Vicentinho",
  "Vicentinho Júnior",
  "Victor Mendes",
  "Vilson da Fetaemg",
  "Vinicius Carvalho",
  "Vinicius Farah",
  "Vinicius Gurgel",
  "Vinicius Poit",
  "Vitor Hugo",
  "Vitor Lippi",
  "Vivi Reis",
  "Waldenor Pereira",
  "Walter Alves",
  "Weliton Prado",
  "Wellington Roberto",
  "Wilson Santiago",
  "Wolney Queiroz",
  "Zé Carlos",
  "Zé Neto",
  "Zé Silva",
  "Zé Vitor",
  "Zeca Dirceu",
];

let partidos = [
  "Partido da Mobilização Nacional",
  "Podemos",
  "Progressistas",
  "Partido Popular Socialista",
  "Partido Pátria Livre",
  "Partido da República",
  "Partido Republicano Brasileiro",
  "Partido Republicano da Ordem Social",
  "Partido Republicano Progressista",
  "Partido Renovador Trabalhista Brasileiro",
  "Partido Socialista Brasileiro",
  "Partido Social Cristão",
  "Partido Social Democrático",
  "Partido da Social Democracia Brasileira",
  "Partido Social Liberal",
  "Avante",
  "Cidadania",
  "Democracia Cristã",
  "Democratas",
  "Movimento Democrático Brasileiro",
  "Partido Novo",
  "Patriota",
  "Patriota",
  "Partido Constitucionalista Brasileiro",
  "Partido Comunista do Brasil",
  "Partido da Causa Operária",
  "Partido Democrático Trabalhista",
  "Partido Humanista da Solidariedade",
  "Partido Liberal",
  "Partido da Mulher Brasileira",
  "Partido Socialismo e Liberdade",
  "Partido Socialista dos Trabalhadores Unificado",
  "Partido dos Trabalhadores",
  "Partido Trabalhista Brasileiro",
  "Partido Trabalhista Cristão",
  "Partido Verde",
  "Rede Sustentabilidade",
  "Republicanos",
  "Sem Partido",
  "Solidariedade",
  "União Brasil",
];

export let sortedNames = names.sort();
export let sortedPartidos = partidos.sort();
